name: Ubuntu
on: workflow_dispatch

jobs:
  system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update system
        run: sudo apt update
      - name: Install tmate
        run: sudo apt install -y tmate
      - name: Start tmate session (SSH access)
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          echo "==================== SSH ACCESS ===================="
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "==================== WEB ACCESS ===================="
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'

          # keep job alive
          sleep infinity
